plugins {
    id 'com.android.application'
}

android {
    namespace 'org.farazkevani.sindhidictionary'
    compileSdk 34

    defaultConfig {
        applicationId 'org.farazkevani.sindhidictionary'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
